### ISSUE TITLE
Glyphnames are not swapped

### ISSUE THREAD

**Issue by adrientetar** [twardoch/fonttools-utils#5]
When freezing a stylistic set into the font, glyph `a.alt` is assigned the codepoint of LATIN SMALL LETTER A but isn't renamed to `a`. 
This causes problems in certain apps, e.g. Adobe Premiere on Windows I'm told.

**Comment by twardoch** [comment]
That's by design. At this point, I have no plans to swap the glyphnames. When multiple features are being frozen, it's not trivial to "swap" the glyphnames. But you're most welcome to submit a patch that does this. For now, I've just added a --zapnames option to remove glyph names from .ttf fonts. But for .otf, glyphnames are required, and implementing renaming is a bit tedious.

**Comment by adrientetar** [comment]
> When multiple features are being frozen, it's not trivial to "swap" the glyphnames.

Then maybe a switch that swaps only on single feature freezing can be checked-in? It would be useful for the usual purposes of such a script. 
Working on this script is not part of my appointments just yet – though someone else might be interested in this I suppose.
