### ISSUE TITLE
Replacing string in name tables incomplete

### ISSUE THREAD

**Issue by yanone** [twardoch/fonttools-utils#8]
Hi,

the names don’t get replaced in the *Unique font identifier* field, nameID 3. In other fields they do get replaced, such as nameID 6.
The complete entry of nameID 3 reads `1.001;YN  ;NonameSans-Regular` in my case before the replacement.

The complete call:
`python '/Users/yanone/Webseiten/wsgi/tools/pyftfeatfreeze.py' --replacenames 'NonameSans-Regular,NonameSansOffice-Regular' --features 'lnum,tnum' --suffix --usesuffix 'Office' --info '/Users/yanone/Schriften/Font Produktion/Fonts/NonameSans-Regular.otf' '/Users/yanone/Schriften/Font Produktion/Fonts/NonameSansOffice-Regular.temp.otf'`

**Comment by thundernixon** [comment]
Experiencing this issue, as well. 

Whether I call 

`pyftfeatfreeze.py -f 'smcp' -S -U 'SC' EncodeSansCondensed-Bold.ttf EncodeSansCondensedSC-Bold.ttf --replacenames 'EncodeSansCondensed-/EncodeSansCondensedSC-,3.000;GOOG;EncodeSansCondensed/3.000;GOOG;EncodeSansCondensedSC'` 

or

`pyftfeatfreeze.py -f 'smcp' -S -U 'SC' EncodeSansCondensed-Bold.ttf EncodeSansCondensedSC-Bold.ttf --replacenames 'EncodeSansCondensed-/EncodeSansCondensedSC-'`

or simply

`pyftfeatfreeze.py -f 'smcp' -S -U 'SC' EncodeSansCondensed-Bold.ttf EncodeSansCondensedSC-Bold.ttf`, 

I get the same result:

```
  <name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2018 The Encode Project Authors (https://github.com/thundernixon/Encode-Sans), with Reserved Font Name 'Encode Sans'.
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Encode Sans Condensed SC
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Bold
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      3.000;GOOG;EncodeSansCondensed-Bold
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Encode Sans Condensed SC Bold
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 3.000
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      EncodeSansCondensedSC-Bold
    </namerecord>
  </name>
```

If I just run `pyftfeatfreeze.py -f 'smcp' EncodeSansCondensed-Bold.ttf EncodeSansCondensedSC-Bold.ttf --replacenames 'EncodeSansCondensed-/EncodeSansCondensedSC-'`, I get:

```
<name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2018 The Encode Project Authors (https://github.com/thundernixon/Encode-Sans), with Reserved Font Name 'Encode Sans'.
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Encode Sans Condensedsmcp
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Bold
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      3.000;GOOG;EncodeSansCondensed-Bold
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Encode Sans Condensedsmcp Bold
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 3.000
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      EncodeSansCondensedsmcp-Bold
    </namerecord>
  </name>
```

...which is definitely not what I want.

Interestingly, `-replacenames` does work to an extent, because running `pyftfeatfreeze.py -f 'smcp' EncodeSansCondensed-Bold.ttf EncodeSansCondensedSC-Bold.ttf --replacenames 'Encode/Test'` results in:

```
<name>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2018 The Encode Project Authors (https://github.com/thundernixon/Encode-Sans), with Reserved Font Name 'Encode Sans'.
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Test Sans Condensedsmcp
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Bold
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      3.000;GOOG;EncodeSansCondensed-Bold
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Test Sans Condensedsmcp Bold
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 3.000
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      TestSansCondensedsmcp-Bold
    </namerecord>
  </name>
```

However, this still doesn't affect name 3, the unique font identifier, either. I wanted to do a PR on this, but I'm having a hard time following how the code updates the name tables. If anyone can give me a bit of a push on this, I'd also be happy to take a stab at fixing this myself and PRing.

**Comment by madig** [comment]
There is no code to update nameID 3. I'm working on this, my current implementation does

```Python
            # Unique ID. Do not search and replace strings here because a unique ID
            # is essentially an arbitrary string.
            if nr.nameID == 3:
                nr.string = f"{oldname};featfreeze:{self.options.features}"
```

to produce e.g. `1.001;NONE;Test-Regular;featfreeze:smcp,c2sc,onum`.

**Comment by madig** [comment]
Should be handled in master now.
